<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>01_ProviderSetup</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5f2941a6-1d00-42d6-8048-ee358106af83</testSuiteGuid>
   <testCaseLink>
      <guid>4e695a9e-fcd0-4bc0-ac27-c3bb1d799246</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/01_ProviderSetup/PS01_ValidateProviderSetupPageUI</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0c865774-4f13-450e-9708-56f289ec1bfe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/01_ProviderSetup/PS02_ValidateProviderSearchTextBoxFunctionality</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1ffc23ff-fe64-4265-9531-9325f99826e0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TeamHealth/01_ProviderSetup/td_PS02_ValidateProviderSearchTextBoxFunctionality</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1ffc23ff-fe64-4265-9531-9325f99826e0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProviderSearch</value>
         <variableId>2d0597cf-208f-4d2f-a164-41666351138f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>beeddad1-f259-4553-80c5-17ca2209d90e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/01_ProviderSetup/PS03_ValidateUniversalSearchFunctionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6289ef3b-637e-49a9-a26c-b365535b560c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b7841eee-9bd3-4cbe-8c6e-8eb9eaa3803d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/01_ProviderSetup/PS04_ValidateClearButtonFunctionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c8f4bb6-ead5-4db2-b841-79029b197189</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd859879-ace2-401c-9f32-06d58a7b5b40</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>42f32d5f-8dd6-4c34-8cac-fcb7069b565d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/01_ProviderSetup/PS05_ValidateExportProvidersInformationImageFunctionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8ff0faa-02d6-4dac-aabb-c12150528f50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7038b0c-10e8-4c85-83f7-870349a85546</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/01_ProviderSetup/PS06_ValidateRegionIsDisplayedBasedOnTheUserRoleAccessPermissions</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e97dc21-8e69-47f5-87bd-8333f16be8f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b1017d4-ab3d-4e1b-9fd8-94b7c95efcb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a64bc428-7731-455f-96ba-75b744b8ae62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf07df70-c892-4844-a7df-7b6ddfac21de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/01_ProviderSetup/PS07_ValidateLocationDropdownList</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b623715-2f74-4033-b37c-f854b32cf4ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>144fb482-7d98-4f6d-98f7-2bc67e7bc771</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/01_ProviderSetup/PS08_ValidateCostCentersDropDownsList</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdf8f51b-fdc0-4eb1-b566-6a970256db54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e5c93cd-4e14-4f51-a70d-430d79962189</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78cbfc43-f948-4e5a-9323-dd3638149fa0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/01_ProviderSetup/PS09_ValidateProviderGroupDropDownList</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7934cfa8-7b76-4a83-a1ff-e67b4201a057</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/01_ProviderSetup/PS10_ValidateSpecialtyDropDownList</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d99a3744-5e80-403a-9b07-91a74a2ddb74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/01_ProviderSetup/PS11_ValidateProviderGroupDefaultValueBasedOnGeneralSettings</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bf6b609-247b-463f-9cd1-6135dc0f5c30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b77ba028-aae4-4161-a789-5f477fbc8f7c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac0c3578-b4a5-46ee-8aba-d676a7317a51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/01_ProviderSetup/PS12_ValidateEncryptedDataBasedOnGeneralSettings</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6295695b-66a0-4943-b821-746e02a1e922</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d071c3c-8fea-4cb1-80aa-d17d3da51a33</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/01_ProviderSetup/ValidateCreateProviderWithAutomatedTestData</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
