<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PaymentProcess</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ef88ac8d-8591-42df-be02-0fc06483ad8c</testSuiteGuid>
   <testCaseLink>
      <guid>de7575eb-f9c6-463b-8061-34c6ed0dac84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/05_PaymentProcess/PP01-PP02-VerifyPayPeriodDropdownForOrangeColor</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>145412f6-ed34-4d25-ba1a-76c8ff86c7e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec19b352-7891-43a3-88a8-fdfec3ce755f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36c05532-61a5-4b77-b4c4-04d2bfe338db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fefa738d-fb56-40d5-b377-4456e4563f4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f91780ca-82dd-42f8-9171-fd577df94dfb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7a7e660-d982-4df9-bda9-1ef2f9d24af6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>906a3c8e-d287-4c18-b774-321a184e865f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/05_PaymentProcess/PP03-VerifyLoggedInUserAbleToDeleteCompletelyProcessedPayPeriod</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>145412f6-ed34-4d25-ba1a-76c8ff86c7e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec19b352-7891-43a3-88a8-fdfec3ce755f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36c05532-61a5-4b77-b4c4-04d2bfe338db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fefa738d-fb56-40d5-b377-4456e4563f4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f91780ca-82dd-42f8-9171-fd577df94dfb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7a7e660-d982-4df9-bda9-1ef2f9d24af6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c00f7ae2-5e4e-4ee1-bc2e-5fc5a471b6df</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9cde754b-8af7-49b6-bfa9-b53b6aa0eba9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/05_PaymentProcess/PP04-VerifyWhetherTheLoggedUserAbleToProcessAssignedRegionsORLocationsPartially</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40b156e1-63e8-4f85-8358-b31a9e140a98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>050e5d70-858c-47e2-b78a-27b39436321d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2606cdb4-68f6-45b4-930e-d640688ee33c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddd80c49-97e7-4294-af92-5c6d1e0dc1e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5377a76f-1693-4ab0-8d1f-ff0678ee0797</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe9c60f5-8498-4a56-8c90-93026e7805f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/05_PaymentProcess/PP05-PP06-PP07-PP08-VerifyAlertPopupProcessCompensation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40959fb9-0601-4d45-b46c-90a96ed23fa7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e451602-f5d9-4bf3-b01c-31d5185828ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b082a9f8-5423-4589-a541-0e1979a72249</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4f991cc-969c-44e1-a640-90991884b7d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ae63c8b-5c14-4b9a-97f5-d54f852a7555</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0530295c-a14e-4882-b1c8-b7c553a257bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>63739188-5b0e-48ca-9958-ec5fda9ba240</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/05_PaymentProcess/PP09-PP10-PP11-VerifyMaxCompensationErrorMessageAndCostCenterBackgroundColor</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f679305-e55f-4b96-bbd5-88429734bea2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03c207a0-3e71-4542-b155-a7e7b7cffe01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>689dccb6-c75b-4f89-9e41-692b9cf233e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe060ca9-9fe3-4cf8-aea9-dc51ce55f9ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26a1a360-a899-4374-8e03-fbb6a4ac27ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a319e54d-79d1-4fa6-a3db-1ff7a9ebdf26</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/05_PaymentProcess/PP12-VerifyWarningMessageForNotGiveContractedHoursForRegularBasePayElementInTheContract</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f679305-e55f-4b96-bbd5-88429734bea2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03c207a0-3e71-4542-b155-a7e7b7cffe01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>689dccb6-c75b-4f89-9e41-692b9cf233e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe060ca9-9fe3-4cf8-aea9-dc51ce55f9ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26a1a360-a899-4374-8e03-fbb6a4ac27ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60c8413d-fec4-4845-9e52-d5af97bd4076</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/05_PaymentProcess/PP13-PP14-PP15-PP16-PP17-VerifyPayElementData</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13bfe6c0-79d8-4df6-825e-5e249774c366</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb6b6527-92d5-482b-b119-309ddf8a5e91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d151def1-f6c3-49b8-bf63-c8e260579d6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b3fbfc2-87e1-42cc-b8eb-76c494d7b502</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53f92aec-eaf1-40ff-a62c-9678c09b49b6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a01993c-d9db-468d-b56d-11385aee9694</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/05_PaymentProcess/PP18-VerifyPaymentProcessGridColumnHeadings</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>145412f6-ed34-4d25-ba1a-76c8ff86c7e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec19b352-7891-43a3-88a8-fdfec3ce755f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36c05532-61a5-4b77-b4c4-04d2bfe338db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fefa738d-fb56-40d5-b377-4456e4563f4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f91780ca-82dd-42f8-9171-fd577df94dfb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7a7e660-d982-4df9-bda9-1ef2f9d24af6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c00f7ae2-5e4e-4ee1-bc2e-5fc5a471b6df</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b54f1ec-5c71-4a9f-826c-4e5d39e36823</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/05_PaymentProcess/PP19-PP20-PP22-PP23-VerifyGLAccNoHIICCID</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da053c35-9f36-4b1b-91e3-e67aedc5068f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96cde587-3008-4147-bfa1-39b72999c563</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc298cc0-c49d-4d25-83ac-21e4ea847246</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a402974-a1da-49ed-8227-fa5b3df7dcc0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b8792fb-86b1-4f05-b69a-002e5a6b4746</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37fe72f3-63eb-450d-b1a6-0d0b20da4885</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/05_PaymentProcess/PP24-PP25-PP26-VerifyAbleToSearchProviderInProcessByProvider</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>145412f6-ed34-4d25-ba1a-76c8ff86c7e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec19b352-7891-43a3-88a8-fdfec3ce755f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36c05532-61a5-4b77-b4c4-04d2bfe338db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fefa738d-fb56-40d5-b377-4456e4563f4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f91780ca-82dd-42f8-9171-fd577df94dfb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7a7e660-d982-4df9-bda9-1ef2f9d24af6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c00f7ae2-5e4e-4ee1-bc2e-5fc5a471b6df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b3f55c6-0d3a-4f96-b69c-c8659798fa43</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca1a1ee4-29aa-474f-b5d6-7bc02f3c91d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/05_PaymentProcess/PP26-PP27-VerifyAbleToSearchMultipleProvidersInProcessByProviderAtOnce</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>709e9872-d87c-4b5b-a73b-aef2309c2f09</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b7ab9ab-dd22-461f-957a-271192fbceb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7dc7e29d-5b73-4c2d-b51c-bba71c962638</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>922b1521-7c53-427c-a81f-86cabbeb418f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df9d253e-c373-409d-ba89-c7ba2d75d1d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc5e4b9c-7903-4e2f-b5d2-74557decaca7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fdb0eff-8249-4d2d-9a1d-70279638e7e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d22f1fcc-8cc3-4052-b47b-1e546298c35d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/05_PaymentProcess/PP28-VerifyProcessByProviderCannotBeSelectedAfterClickOnProcessCompensationButton</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f2d488f-da19-45e9-b7b0-28b1a63b2658</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a0e8352-70dc-45fc-9e3d-0bf2419a9691</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0ef47bf-9e9d-43f7-8f09-609b19e11f26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c146672-81bc-4109-be45-38987d0743e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>860a83cd-0d0c-49ae-8632-f3fb57836e4b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0236f064-7c33-4f45-8b35-b6f7f978d656</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/05_PaymentProcess/PP29-PP30-PP31-VerifyProvidersAfterSendToPayroll</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8c61a1d-883a-4848-9224-ae72dbaab81e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38ff821c-0453-4957-b14c-af13b3f9dfd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47f7e202-9af2-4766-9798-cca3aca0cab7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08cd59bf-fa88-4d08-a04e-e8389bb93d32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82d0e56f-56ba-4291-84c9-0d778214c51b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3eff0636-7b10-49e0-912b-8e83779f31c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7110843d-d881-4bb5-bba0-8a535c9eb22d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
