<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ProviderPayApproval</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>6d6de953-fc5c-4fc0-8fa0-f8652a86ceee</testSuiteGuid>
   <testCaseLink>
      <guid>63f2b01e-efe2-4ee0-a290-f344636fa01f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA01_VerifyProviderNameWebServiceFunctionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85711561-7c15-414c-b94a-1a4f1c87242b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80582f51-a01c-48e3-b2d0-b96deff8e45d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>653661ea-41a9-4572-8323-3916e76e2318</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA02_VerifyRegionIsDisplayedBasedOnTheUsersRoleAccessPermissions</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7bebceb-c27c-41af-a226-a20ab986671d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dabc4ff1-84ab-4a45-a200-f94e582e1bb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13e77221-8ab1-4d11-b027-ba8bc1e8cc0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89cb7504-1567-48b7-85a9-6e994c00e9be</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e46dbc79-4c6c-46ba-81f9-cee0e64b5d55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA03_VerifyPayCycleDropdownValuesAreDisplayedBasedOnTheSelectedRegion</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2ce6dc3-a538-4acc-927c-80267e7235d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>191e8d1f-3889-4acd-849e-13aa3a20cc19</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA04_VerifyLocationsDropdownBasedOnTheSelectedRegionAndPayCycle</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f898a17f-ce2c-42ca-b6da-30badf5f0e9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>016d84c3-758b-4402-accd-c9671c5784f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a8c084b-6704-4229-8034-e19e06175931</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA05_VerifyPayPeriodValuesDisplayedInThePayPeriodDropdownField</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6790eecf-e927-4acc-a95f-53d921372cc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ed3e0c4-72ff-44d8-bf6c-4aee8aaf4a5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>738694e8-5c58-4fda-ae0a-f8139867dc79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab0d6f2d-2a46-4969-b3f7-ed6b2928cf46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e4c1905-27a4-492e-85d7-177ed11f90dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d12d40fd-7f9a-44dc-abae-0d0bde4f8275</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd23632b-5a02-4b7b-a7e9-3500662603bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA06_VerifyPayElementsDisplayedInThePayElementsDropdownField</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5d30407-6271-4c0a-9843-13ff7d1e8a30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd50511b-595e-4f8d-a386-d0d30922a5b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1d5d8d1-c94f-4fea-8d5e-30ee809847f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6575782-bd68-4f27-b835-ca08e4eb2919</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>488e2415-ebbe-4688-947f-5666571bcf01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>825842cf-3e1b-49b6-b33b-941e3dbed3bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78773cb4-7502-4637-aa5d-36a781e0a2b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>549ee8b0-16eb-4d3d-b63f-31043ee6d788</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>454f0904-9774-4236-9653-6db972996fa1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA07_VerifyCostCentersDisplayedInTheCostCentersDropdownField</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ef2df7d-9862-4634-a517-be14c32460e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8caf17a8-93a9-4985-a37c-10550580d3c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>238201d6-a29b-49b2-b6fe-1ea324b5ac04</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70344370-3527-4a77-8e28-f81d76a2a7b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA08_VerifySpecialtiesDisplayedInTheSpecialtyDropdown</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b2ac2b4-8e8f-42c5-8935-6dcb50798983</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4f1eb37-8295-4705-98b0-6ceae678e79f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a93c474d-20db-4fa4-9d44-2dceaf04f28b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ab47cf66-6719-4758-9821-9dbb674a27b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA09_VerifyInActiveCheckboxFunctionalityInPayApprovalsScreen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10060aec-1b43-4dae-aac1-9796784eae74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1671a93c-5cf4-4dbe-b28c-640064cb3340</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>55569e59-9af5-4027-bd06-efda94bd88d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA10_VerifyShowAdjHoldCheckboxFunctionalityInPayApprovalsScreen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4df236cb-5a1e-43c4-876f-8c54894ad3ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ebe8e5f-b597-4ebf-ab10-9cd9d82e1a29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7407be30-cec1-41a7-9079-b3ca3976a090</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2038596-2a38-49f2-a3ef-bdfaae332ec9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1f631d4-c650-47bf-bf2e-e9c627e2bc7d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d07253c1-a14f-4ccd-bf85-a87c41554e96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA11_VerifyAbleToApproveORDenyThePayRequest</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9e6aa6b-93d7-4fbf-9d7f-47097a4e81fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfbba233-19a3-400d-b49b-3c8bae06a299</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57ea9027-f86c-4e71-94c1-647189b18734</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7efa1cc8-402e-4a55-9059-cfd89dfc5952</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d2bae2f-2dfa-48e5-9530-1663539ad9ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86f6a900-f9f6-4883-8b20-190bdeb04883</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93be4b32-4a24-4ad3-bcf0-2ed023cb93a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f221515-3c48-4454-828c-e1d101350db0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6599455-1b02-4419-8d1b-268bb90e39bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66bb6a28-bbb1-4dc5-9bb3-a4457d1b703c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc455045-e200-4d6a-baa9-d8988e46fa35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3017078-06ec-40e3-87fe-0e0099170595</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ba62462-b4ed-449b-ad75-ce17a99dedaa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f16f3605-e32b-4cbd-8a69-8a4110ecb52f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA12_VerifyPayRequestUpdatedAsRejectedAfterMeeitngTheDenyLimit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f2c4106-0ccd-4a1b-897f-75196b0c5c55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6f95431-71de-4eee-9d57-eb7130ca3015</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a60e6937-7088-46d0-8265-23899044afcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff8948bf-fd68-40a7-a522-e9e8111b8aa8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e07e960-8b4b-445b-910e-53b9060691ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d48264e-9525-489a-84ec-9f40f3fa2155</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57792d5e-29d9-4162-819d-341cbdb9be6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e086579a-df1d-4439-9874-0774c2bb4115</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA13_AbleToDownloadTheAttachmentWithOutAnyErrorWhichIsAddedWhilePayRequest</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b29ac2a6-5bdb-41c3-b8ce-986c968bcf2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13e8c5f3-fd20-474b-93e1-1cd7e89cd1ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e848496-d06f-4b7e-8e69-f05d7119c4a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92a4c622-8285-4f5b-8920-9f98048fa986</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>476acf1f-add0-4395-8eda-69877741bf1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2e5da5ed-e762-4791-a9c7-e9644a886ddc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA14_VerifyFunctionalityOfDownloadExcelIconWorkingProperly</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e7147a2-ec16-434c-af13-1f40c3c6331e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3eb72df8-871f-46eb-b871-c1772fcb8882</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e7f6800-52b6-41e1-88c7-cb87ee5dfa5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA15_UnitColumnCanBeUpdatedAndTheAmountShouldBeReflectedBasedOnTheUpdatedUnits</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52a046d7-62b1-4986-8ee1-4866e0fd8596</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a77486bd-2820-41f0-9e67-c693139b57d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a7c19c5-ff6c-4afb-b98b-7c2caaf1a0d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f63be783-e49e-43d3-af3c-c4e13614e911</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0d3a714-7911-4d63-8302-5488ecca92f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01e129ad-2fdd-40d8-a646-2bf6d2730931</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a85c358-4855-448f-8ebe-6025d54df08e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA16_PayPeriodAndPeriodColumnDataBasedOnTheSinglePayRequestAndPayRequestImport</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33c89e86-a733-47df-86ce-4dcf7d76d554</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4965c11-506b-4dc6-92c2-c5ff4227f7e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>786163e3-8ab7-46e8-a37a-c6f7848679d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08cf7d0f-4dcf-4265-9757-5194a75bf7e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA17_VerifySendToNextApproverFunctionalityShowingMaxCompensationOrThresholdAlerts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32b630fc-925e-4e45-80b6-b1a42c0dfaa6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbcf3c70-5d7e-46d0-a7a9-69aad9ef5179</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>958748f6-5c10-45f5-b3de-a15b73e64943</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3789b59-4972-409c-8c24-96fdbd73d219</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40c65b70-6d09-44f0-a9d9-9b9b8d359b37</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4deaa2d4-a99a-47a0-bad7-ae7650c80d06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/04_ProviderPayApprovals/PPA18_UpdateFunctionalityShowingMaxCompensationOrThresholdAlerts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99f5f15b-a9dc-48d5-8ec8-93879176b450</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5448e13-5b66-411c-a2da-a498125a40a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59fbe9f0-7e9b-4800-a7ce-fc8906ad3d54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84517a50-bcaa-4c39-ac71-42283bd6f4ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41c58098-3ea7-4622-9c2e-3cc4d881ac70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5900a28-f186-413d-b3fb-67b56068617f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
