<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ProviderPayRequest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e4ac4e73-8a4c-414b-834a-ea6553e822fe</testSuiteGuid>
   <testCaseLink>
      <guid>80272a73-1843-4688-b9c1-37dd9baf2e96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR01_VerifyProviderNameWebserviceFunctionalityInSinglePayRequest</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c86acdec-abe0-4cdd-94e1-caa2be961d94</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae746206-1534-4d5a-be39-3a0072c870c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR02_VerifyServiceDateFieldWhenTheFlagIsTurnedONInApplicationSettingEnableStartandEndDatesforthePayments</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20fcab17-9a89-4149-8593-d3fdd4a8e8dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9264021-539e-4a59-b536-9e3249c3d010</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f90e36c-fc4f-459c-8a23-6a547d6fee1f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a89799fa-e053-4b00-b237-d1b1fa85dc64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR03_VerifyServiceStartDateFieldInSinglePayRequestScreenIsShownBasedOnTheApplicationSettingsFlag</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>cdbee72d-ea3d-4f2b-b4c0-34eeb670dba5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR04_VerifyServiceDateFieldWhenTheFlagIsTurnedOFFInApplicationSettingEnableStartandEndDatesforthePayments</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb138d99-9222-4f8b-b57f-b909c416025c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e9ccbc2-374d-4f43-be95-6a3623048f3a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>99205578-f881-4000-9184-ca1d545f4521</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR05_VerifyTerminationDateIsOnlyDisplayedWhenTerminatedProviderNameIsSelected</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41774c76-75e2-4351-a219-a095eafe7e64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6dd80d35-a5cd-4ecb-b240-43b21d4b1c4f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR06_VerifyCompModelDropdownFieldInTheSinglePayRequestScreen</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0495f38-8b84-4aa4-a3ca-140267cd9c27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa2e80f5-29b8-4cb8-8007-11897a15b2a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1cd010d-3563-4343-882d-d3686e1e2223</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e07987ec-012e-4c02-a213-083a5938a1d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR07_VerifyThePayElementsListedDropdownInThePayElementDropdown</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fd3dd96-7f3e-4daa-8617-b4264bbb3883</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11f471b6-9111-4b75-8b77-4b565eafad1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1161859-efe9-46f8-86a6-5b2e6b9181da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5346cea6-4551-4c77-8957-865f362cd36d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>25d5ffcd-06e4-4d9f-9b82-91c928944d98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR08_VerifyPayRequestNoteMandatoryBasedOnPayElementMaster</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d3c2841-8b09-4713-bcd1-9bba1ab161e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>123324e9-0540-497e-9d1c-002276037222</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>884c4ae5-9fb1-457f-b995-a7e15fe2c8e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e91cd1c-3ad8-4c02-814a-04d434a9cf45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17151498-1e19-4f71-b428-0d7782ec5102</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1ab89a1-888f-4edc-9905-04ec253ee3bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>adc5855f-51d7-4c25-aa46-f6b375eaa46c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR09_VerifyUploadFilesMandatoryBasedOnPayElementMaster</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d3c2841-8b09-4713-bcd1-9bba1ab161e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>123324e9-0540-497e-9d1c-002276037222</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>884c4ae5-9fb1-457f-b995-a7e15fe2c8e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e91cd1c-3ad8-4c02-814a-04d434a9cf45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17151498-1e19-4f71-b428-0d7782ec5102</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1ab89a1-888f-4edc-9905-04ec253ee3bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>669083c3-26f8-40ae-aac6-d5b4dd346311</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR10_VerifyCreatingAPayRequestByProvider</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d1cf4c4-e398-4e98-82b5-56ae3b34be3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>baad5b54-2c55-461b-a1e5-dbf82641560e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>997eb2ce-3046-47f2-95c3-9f028507d726</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53500d37-d596-4857-9177-a5c8ecf932c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b797a4ff-6958-4131-ad33-ee6af4692154</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46400ca2-5808-4b99-ace3-e88e06cab93e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>adef5fcb-a8eb-4830-a5dc-f06edcf55f23</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>534a3e90-6e24-443a-a408-eeba2fe69755</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR11_ToVerifyTheValueDisplayingInTheYTDAmount</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf7fca85-22ed-42cd-9dda-5009879724cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d67a35b7-ecbb-42b0-99d8-78e14a8405a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7762487-301f-42c5-aad0-67874550f95f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89b6a736-f289-44db-9f23-1b8223d0b297</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c5aaa8f-89d2-47e7-838a-e74faad55d7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b5eb320-b7b4-4f96-ae84-b4a36fbd941b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4f9e917-13f6-4223-b558-69bd9fbd998f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR12_VerifyCreatingPayRequestByCompensationAdminsistrator</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb378b40-067a-4b87-b10a-5bc5130a6b15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af72140e-f3ae-4c58-a2b7-8d648adeea8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b33a49f8-e706-4e66-8120-03ef77b270f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e09c1929-517f-4e8b-8899-d5b1d5caa1f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59543977-c092-4266-a0fc-ef2d909bcd19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28e26518-da97-4712-a40d-9b0d28265fb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d048c6a-416e-465c-869f-b76cd16acfd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b628fe1e-2d0b-4148-b34d-2e61dd3de4d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70ebf164-85aa-4d44-9f06-fa6571546c7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66357a16-50f0-446e-ac0f-deb7d900b131</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c51b8c8-2ebb-4c5c-8e37-cfd5191a0bab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a88608cd-3ec9-491d-a851-1a07d8e72433</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2101df76-0046-44cb-890b-68602a26c78d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR13_VerifyUpdatingPayRequestByCompensationAdministrator</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ace74988-c4d3-49bf-9405-560b2421eb8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d91da2d-a5a2-4b08-8769-704ee2a38462</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0de8154b-a486-49d3-b579-41c0ec574355</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>789b4d05-799a-4432-a84d-8c9d35f072f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f5981ef-f8af-4875-bd58-68ba312b11f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92f104f9-bcfc-43d3-8f67-8b412a4ca03b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e40d51a2-748f-44fa-a56d-08fa98f34a1f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR14_VerifyMaxThresoldLimitAlertMessageIsDipslayingWhenUserCrossMaxThresoldUnitsLimit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a26c195d-aabe-43ca-8e01-da5f06c70eb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a8cec59-5cae-46e9-8cd6-ceda39aca487</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae0e1d05-3a06-43ca-9be9-ef7b39c2f3e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea86347c-0ac0-46fe-a5f9-d8b041bee923</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7647e2f6-b15a-47d3-8d81-4986b6312b2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2134c196-f8cc-4b9b-a79e-663b697c17b8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>edbf3949-3178-4ae1-9eaa-feb40ab3aaed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR15_VerifyWhetherTheYellowBackGroundIsDisplayingOrNotWhenThePayElementReachesTheMaxThresholdWhenWeContinue</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f707fc30-924b-4d8a-b050-f9b6c8037c86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>672902de-95de-4319-9620-99406742fefe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad5863a6-354d-4c88-bd18-19dfea52ce64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61e42b10-9957-479b-b0ae-0ad8d5c44df7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bf09adb-54eb-4aa2-9b33-daeb76c3b1fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0396462-848c-458c-832f-7414e6d2fca9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb930024-e353-4e9e-8eef-84daa135c712</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5495231-99db-466b-ad10-bdbc49c59fae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a0e1305-de2f-40d7-92a9-16647c32f7ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66485369-a94d-41a9-a107-249df9962130</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb193cdb-2e02-44b4-b126-f4a39f8e60ef</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0f5699a-9ad1-49de-858a-4a1df0b7ecd2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR16_VerifyWhetherTheYellowBackGroundIsDisplayingOrNotWhenThePayElementReachesTheMaxThreshold</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>922c8392-f3cd-4dba-ad91-842576b0337d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b6ea7d4-86cd-45b8-985a-5dd2a588d0f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94ca042a-8fb9-4c76-9be4-8a4602c97114</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>508d7aff-28e6-4462-9881-db2d78874da3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06f52e07-8066-4413-a7d2-7fe520f0e3fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a42d01b-1c5c-49c4-a198-a6d359c0303f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR17_VerifyPayRequestCreationCancellationWhenPayElementValueExceedsMaxCompensationDurationWithintheContract</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc413f87-38d1-43f7-9eb8-3f62d22f8f00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c58e2d9-e547-4a47-a24e-b35897a5f866</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64371454-d24f-4ba1-920e-6571f56b66fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56a3a822-3395-46c9-a481-942c8c95d7f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>848ed878-20b7-45b2-8dde-ce55c5782776</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7ca6525-2970-47ee-9835-16dae3fe597f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>72276310-d3ee-456c-a001-5cb3966810be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR18_VerifyPayRequestCreationWhenPayElementValueExceedsMaxCompensationDurationWithintheContract</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54ad9052-4aae-4b63-8cc4-77fafcf2dcef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>093c0372-b33a-4cc1-a4ef-0d7ddf4b3a2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79ae2caa-4492-4487-95ec-d0ba039dc192</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2ed75eb-a70c-4032-95c5-4a5b73249afe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85159d37-8ff7-4799-bf6f-7d09d5d72106</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ff19d0e-60ea-429a-8db5-5f7bc847dd4a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0262a5eb-5e3f-491b-9ccc-e97f8819d661</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR19_VerifyPayRequestCreationCancellationWhenPayElementValueExceedsMaxCompensationDurationAcrossMasterContracts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f4adfd6-508c-47fc-955c-39f2034f790d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7febf94-45f4-49c6-87cd-5e6596a08073</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>819bb968-c88c-49a5-8c53-17bd4abfa370</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1afc3261-0e46-44e6-90b7-d65c0b062e70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f7e2836-b16f-4ffd-9769-4591040e9150</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06f1403e-8990-4e56-8a85-a1f086679ea4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c7bb165-addc-4057-a081-6c65e3f64e2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR20_VerifyPayRequestCreationWhenPayElementValueExceedsMaxCompensationDurationAcrossMasterContracts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4eda7668-17ef-459e-af7a-63cccddca3d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e123fc70-d166-444f-bb16-ee555519fb42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ee08d19-33e2-4236-ba67-35036e3134e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d2fe693-1423-4e2e-bdf2-9a14b99db513</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34b9fac9-e160-444b-955f-05e757f95d6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22019e90-b113-4788-a125-bc239776c7e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56ad4569-be50-45d4-b544-90847c69aae7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/03_SinglePayRequest/PPR21_VerifyTheFunctionalityOfDeleteLinkOnceTheRecordIsSaved</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc914ea7-bb30-4a0d-8bf8-8147cd75e801</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b992e06-a9f4-4e57-ae15-e262a513fb5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba72a087-661c-47ca-ad09-8e382eaa87cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7934914d-f091-4748-b48a-7fecde2cce65</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d2dc90c-063f-4385-af7a-e5f7e2339e41</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
