package configs

public class PageLocatorReader {

	public static final String Login='LoginPage'
	public static final String CMN='CommonLocators'
	public static final String ChooseRole='ChooseRolePage'
	public static final String Header='HeaderPage'
	public static final String ProviderPayRequest='ProviderPayRequestPage'
	public static final String ProviderSetup='ProviderSetupPage'
	public static final String ManageProviderContract='ManageProviderContractPage'
	public static final String GeneralSettings='GeneralSettingsPage'
	public static final String CostCenter='CostCenterPage'
	public static final String OrgCompModelsPayElements='OrgCompModelsPayElementsPage'
	public static final String PayElements='PayElementPage'
	public static final String RoleUserWisePayElements='RoleUserWisePayElementsPage'
	public static final String ManageUserInformation='ManageUserInformationPage'
	public static final String ProviderPayApprovals='ProviderPayApprovalsPage'
	public static final String Region='RegionPage'
	public static final String PayCycleMapping='PayCycleMappingPage'
	public static final String PayCycleSetup='PayCycleSetupPage'
	public static final String Location='LocationPage'
	public static final String Specialty='SpecialtyPage'
	public static final String CompensationModelSpecialtyMapping='CompensationModelSpecialtyMappingPage'
	public static final String ApprovalLevelSettingsForRole='ApprovalLevelSettingsForRolePage'
	public static final String YOPMail='YOPMailPage'
	public static final String Organization='OrganizationPage'
	public static final String PayElementColumnConfiguration='PayElementColumnConfigurationPage'
	public static final String CompModelPayElementSettings='CompModelPayElementSettingsPage'
	public static final String ModelWiseProfileTypeSettings='ModelWiseProfileTypeSettingsPage'
	public static final String MiscellaneousProfileSettings='MiscellaneousProfileSettingsPage'
	public static final String PaymentProcess='PaymentProcessPage'
	public static final String ProcessBonus='ProcessBonusPage'
	public static final String ProviderGroup='ProviderGroupPage'
	public static final String GLAccountMaintenanceByPE='GLAccountMaintenanceByPEPage'
	public static final String Dashboard='DashboardPage'
	public static final String ReportPages='ReportsPages'
	public static final String ProviderEMRData='ProviderEMRDataPage'
}
